name: CI

on:
  push:
    branches: [ main, develop ]       # adjust as you grow
  pull_request:
    branches: [ main, develop ]

jobs:
  laravel:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: forge
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
        ports: [ '3306:3306' ]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -psecret"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    # ───── Checkout code ───────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ───── PHP + extensions ────────────────────────────────────────────
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'            # keep prod parity
        extensions: mbstring, intl, pdo_mysql, sqlite3
        coverage: none

    # ───── Composer deps & Pint/PHPStan ────────────────────────────────
    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Static analysis (PHPStan)
      run: vendor/bin/phpstan analyse app --error-format=github

    - name: Code style (Pint)
      run: vendor/bin/pint --test     # fails if style issues present

    # ───── JS toolchain (Bun) ──────────────────────────────────────────
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH

    - name: JS install & build
      run: |
        bun install --frozen-lockfile
        bun run build

    # ───── Run tests (Pest) ────────────────────────────────────────────
    - name: Run tests (Pest)
      env:
        APP_KEY: base64:01234567890123456789012345678901==
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test
        DB_USERNAME: root
        DB_PASSWORD: root
      run: vendor/bin/pest --parallel

    # ───── Trigger Forge deploy on green push to main ─────────────────
    - name: Trigger Forge deploy
      if: github.ref == 'refs/heads/main' && success()
      run: |
        curl -s -X POST "https://forge.laravel.com/servers/938981/sites/2782664/deploy/http?token=ngY98OIJ3UGQ1NRdSYHHZAQLkuQIMITM4d2mhNYP"
