name: Laravel Security Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Regenerate Autoloader
        run: composer dump-autoload

      - name: Install Laravel PHPStan Extension
        run: composer require --dev nunomaduro/larastan --no-interaction --no-progress

      - name: Generate Model Helper
        run: php artisan code:models

      - name: Debug Installed Packages
        run: ls -l vendor/bin/

      - name: Run PHPStan (Static Analysis)
        run: ./vendor/bin/phpstan analyse --memory-limit=1G --autoload-file=bootstrap/app.php app routes database/migrations --level=5

      - name: Run Composer Audit (Check for Dependency Vulnerabilities)
        run: composer audit --no-dev
